| **Language** | **Metric**              | **Number (Minimum)** | **Explanation**                                                                                                                                   |
|--------------|-------------------------|-----------------------|---------------------------------------------------------------------------------------------------------------------------------------------------|
| **Chinese**  | Vocabulary              | 5,000 words          | Words commonly used in daily conversations, media, and intermediate texts.                                                                       |
|              | Characters              | 2,500 characters     | Essential to cover ~95% of written text.                                                                                                         |
|              | Verbs                   | 500 verbs            | Includes auxiliary verbs and common action words.                                                                                                |
|              | Grammar Rules           | 100 structures       | Key patterns such as sentence order, particles (的, 了, etc.), and common nuances.                                                               |
|              | Idioms                  | 200 expressions      | Frequently used idiomatic phrases (成语).                                                                                                        |
|              | Listening Comprehension | 3,000 spoken words   | Ability to recognize tones and common spoken words in various contexts.                                                                          |
| **Japanese** | Vocabulary              | 7,000 words          | Includes words needed for JLPT N2 and daily life communication.                                                                                  |
|              | Kanji                   | 2,000 characters     | Essential for reading intermediate texts (newspapers, books).                                                                                    |
|              | Verbs                   | 400 verbs            | Covers key conjugations like -te form, passive, and causative forms.                                                                             |
|              | Grammar Rules           | 100 structures       | Includes particles, sentence connectors, and polite/honorific forms.                                                                             |
|              | Idioms                  | 300 expressions      | Includes set phrases and cultural expressions.                                                                                                   |
|              | Listening/Phonetics     | 3,000 words          | Recognition of pitch accents and commonly spoken vocabulary.                                                                                     |
| **French**   | Vocabulary              | 4,000 words          | Words covering common conversational and written contexts.                                                                                       |
|              | Verbs                   | 500 verbs            | Includes irregular and frequently used verbs across multiple tenses.                                                                             |
|              | Grammar Rules           | 80 structures        | Mastery of subjunctive, adjective agreement, and prepositions.                                                                                   |
|              | Idioms                  | 300 expressions      | Common phrases like "coup de foudre" or "avoir faim."                                                                                            |
|              | Pronunciation Rules     | 150 rules            | Liaison, elision, and intonation nuances for speaking fluently.                                                                                  |
| **English**  | Vocabulary              | 5,000 words          | Covers conversational and professional contexts.                                                                                                 |
|              | Verbs                   | 400 verbs            | Includes irregular verbs and phrasal verbs.                                                                                                      |
|              | Grammar Rules           | 100 structures       | Covers conditionals, passive voice, modal verbs, and more.                                                                                       |
|              | Idioms                  | 300 expressions      | Examples like "break the ice" or "kick the bucket."                                                                                              |
|              | Pronunciation Rules     | 200 rules            | Includes vowel shifts, stress patterns, and irregularities.                                                                                      |
| **Spanish**  | Vocabulary              | 5,000 words          | Covers daily communication and intermediate texts.                                                                                               |
|              | Verbs                   | 500 verbs            | Includes conjugations across indicative, subjunctive, and imperative moods.                                                                      |
|              | Grammar Rules           | 80 structures        | Focus on reflexive verbs, ser/estar distinction, and subjunctive triggers.                                                                       |
|              | Idioms                  | 300 expressions      | Common phrases like "tener ganas de" or "estar en las nubes."                                                                                    |
|              | Pronunciation Rules     | 150 rules            | Stress rules, rolling "r," and vowel sounds.                                                                                                     |
| **Russian**  | Vocabulary              | 6,000 words          | Words for conversational, written, and professional use.                                                                                         |
|              | Verbs                   | 500 verbs            | Covers aspects (perfective/imperfective) and conjugations.                                                                                       |
|              | Grammar Rules           | 120 structures       | Includes case declensions, verb aspects, and word order flexibility.                                                                             |
|              | Idioms                  | 300 expressions      | Common sayings like "яблоко от яблони недалеко падает."                                                                                         |
|              | Pronunciation Rules     | 200 rules            | Mastery of vowel reduction, stress patterns, and consonant clusters.                                                                             |
| **Malagasy** | Vocabulary              | 3,000 words          | Covers basic communication and intermediate reading.                                                                                             |
|              | Verbs                   | 300 verbs            | Includes regular, irregular, and focus-based verbs.                                                                                              |
|              | Grammar Rules           | 50 structures        | Focus rules, reduplication, and syntax essentials.                                                                                               |
|              | Idioms                  | 150 expressions      | Includes proverbs like "Ny tody tsy misy fa ny atao no miverina."                                                                                |
|              | Pronunciation Rules     | 100 rules            | Intonation patterns and vowel harmony rules.
